apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-container
        image: local-web-app:latest
        imagePullPolicy: Never # Forces Kubernetes to use the image we loaded via kind
        ports:
        - containerPort: 80
